### ISSUE TITLE
Typo in parameter for frame id

### ISSUE THREAD

**Issue by SirVer** [KumarRobotics/imu_3dm_gx4#23]
The launch script uses `"frame_id"` ([source](https://github.com/KumarRobotics/imu_3dm_gx4/blob/master/launch/imu.launch#L13)) as the parameter for changing the frame id, but this parameter is actually ignored. The c++ code actually checks for the parameter `"frameId"` ([source](https://github.com/KumarRobotics/imu_3dm_gx4/blob/master/src/imu_3dm_gx4.cpp#L169)). I think the c++ code is a copy&pasto and should be fixed.

**Comment by versatran01** [comment]
Fixed. Thanks for pointing out.
