### ISSUE TITLE
ROS Kinetic?

### ISSUE THREAD

**Issue by SunggooJung** [KumarRobotics/imu_3dm_gx4#26]
It it possible to execute on ROS kinetic?

for my case it cannot find the usb device.

ROS Kinetic, Ubuntu 16.04.01 LTS

**Comment by kartikmohta** [comment]
Yes this works fine on ROS Kinetic/Ubuntu 16.04. There may be a permission problem if it cannot find the USB device.

**Comment by JHzss** [comment]
@kartikmohta I need your help! How can I get the permission? When I launch the file, it shows me "Exception: Failed to open device",And my device is 3DM-GX5-25. When I use it in my PC,it's works, and it's ROS indigo/Ubuntu 14.04. But in ROS Kinetic/Ubuntu 16.04 in my laptop, it doesn't work. Thanks for your help!

**Comment by kartikmohta** [comment]
You need to make sure that you have permission to access the serial port. This requires your user to be part of the dialout group on Ubuntu. See the first answer here: https://askubuntu.com/questions/58119/changing-permissions-on-serial-port.

**Comment by JHzss** [comment]
@kartikmohta It works!Thanks for the quick reply!
