### ISSUE TITLE
cannot get the filtered data

### ISSUE THREAD

**Issue by alexsaso** [KumarRobotics/imu_3dm_gx4#29]
Hi,

I have a **MicroStrain 3DM-GX5-25 IMU/AHRS**. In the launch file I enabled the filter (see my launch file below), in order to get the readings from the EKF (Kalman Filter). When I connect the IMU and start the launch file, I check for the topics using the rostopic list command. I can see the /imu/filter topic, but when I try to see the msgs of that topic I get the following error msg.

`ERROR: Cannot load message class for [imu_3dm_gx4/FilterOutput]. Are your messages built?`

Did anyone encounter similar issue, or does anyone know what I am doing wrong? Is it even possible to get the filtered messages using this drivers? 

Kind regrards,
Alex Saso  

<launch>
    
    <arg name="output" default="screen"/>
    <arg name="imu" default="imu"/>

    
    <arg name="device" default="/dev/ttyACM0"/>

    
    <arg name="gravity" default="9.81627"/>

    
    <arg name="verbose" default="false"/>

    
    <arg name="frame_id" default="$(arg imu)"/>
    <arg name="fixed_frame_id" default="world"/>

    
    <arg name="baudrate" default="115200"/>

    
    <arg name="imu_rate" default="1000"/>
    <arg name="filter_rate" default="500"/>

    
    <arg name="enable_magnetometer" default="true"/>

    
    <arg name="enable_filter" default="true"/>

    
    <arg name="enable_accel_update" default="true"/>
    <arg name="enable_mag_update" default="false"/>

    
    <arg name="enable_tf" default="$(arg enable_filter)"/>

    <node pkg="imu_3dm_gx4" name="$(arg imu)" type="imu_3dm_gx4" output="$(arg output)">
        <param name="device" type="string" value="$(arg device)" />
        <param name="verbose" type="bool" value="$(arg verbose)"/>
        <param name="baudrate" type="int" value="$(arg baudrate)" />
        <param name="frame_id" type="string" value="$(arg frame_id)"/>
        <param name="gravity" type="double" value="$(arg gravity)"/>
        <param name="fixed_frame_id" type="string" value="$(arg fixed_frame_id)"/>
        <param name="imu_rate" type="int" value="$(arg imu_rate)" />
        <param name="filter_rate" type="int" value="$(arg filter_rate)"/>
        <param name="enable_magnetometer" type="bool" value="$(arg enable_magnetometer)"/>
        <param name="enable_filter" type="bool" value="$(arg enable_filter)"/>
        <param name="enable_accel_update" type="bool" value="$(arg enable_accel_update)"/>
        <param name="enable_mag_update" type="bool" value="$(arg enable_mag_update)"/>
    </node>
</launch>

**Comment by versatran01** [comment]
You probably forget to source the workspace in a new terminal?

**Comment by alexsaso** [comment]
Thank you very much @versatran01, that was the issue. I did not source it in the terminal that I wanted to see the filtered messages. 

I am closing this issue.
