### ISSUE TITLE
Could not find FilterOutput.h

### ISSUE THREAD

**Issue by tanmayd26** [KumarRobotics/imu_3dm_gx4#32]
Hello I am not sure where is `filteroutput.h` file is in the repo. Thank you for your help.

**Comment by versatran01** [comment]
It is a custom msg which is generated by ros

**Comment by tanmayd26** [comment]
![Screenshot from 2023-11-28 08-04-40](https://github.com/KumarRobotics/imu_3dm_gx4/assets/51013316/e3a0b98d-4fba-4ea3-919b-273f7b9ea45e)

Still gives me error and not sure why my ros is not generating it.

**Comment by tanmayd26** [comment]
/home/autorally/catkin_ws/src/autorally/autorally_core/src/StateEstimator/StateEstimator.h:68:10: fatal error: imu_3dm_gx4/FilterOutput.h: No such file or directory
 #include <imu_3dm_gx4/FilterOutput.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I still get this I don't know why
