### ISSUE TITLE
Timeouts beginning with baud rate selection

### ISSUE THREAD

**Issue by ryfallon** [KumarRobotics/imu_3dm_gx4#7]
I'm getting the "Device rejected baud rate" error at the default 115200. I'm able to communicate with the 3DM-GX4-25 using the MIP Monitor Windows program using the same serial port (shared through a 13.04/Hydro VM when using this ROS code; compiles fine). Are there any settings I might need to change within this code or on the 3DM-GX4 itself?

**Comment by gareth-cross** [comment]
I have experienced a similar issue when I launch the node immediately after connecting the device. Usually if I wait 10-15 seconds and try again there is no problem. The issue is sometimes difficult to reproduce.

How repeatable is the problem?

**Comment by ryfallon** [comment]
So far it's every time. I tried moving to a different serial port (over USB) and was able to get slightly further, this time getting through the device info but hitting a timeout on the "Idling the device" step. Oddly enough the next time I ran it it then went back to failing on baud rate again.

This also seemed reminiscent of the older ROS package, microstrain_3dmgx2_imu. I was originally using it mostly successfully with a 3DM-GX3-25 but it was also pretty finicky while starting up, and didn't like starting after stopping either.

Any ideas?

**Comment by gareth-cross** [comment]
Now that you mention it, I recall problems with the idle command as well. Sometimes after the 'idle' command was sent, the device simply would not resume and had to be power cycled. With 14.04 (also in a VM - Fusion on OS X 10.10) I don't usually experience any issues. 

I realize it's not an ideal solution but it may be worth testing on 14.04 to see if this helps.

With your 'Device Rejected Baud Rate' error there should be an accompanying string, one of the following:
(a) Received NACK with error code...
(b) Timed-out while...
(c) Some system message produced by `strerror(errno)`

What else does it report when failing?

**Comment by ryfallon** [comment]
It's almost always "Timed-out while reading". I tried futzing around with the timeout value in case there was some arbitrarily higher lag in the comms but that didn't help. I'll see if it goes in 14.04... perhaps there's some difference in boost behavior?

**Comment by ryfallon** [comment]
Update, it's doing the same thing in my 14.04/Indigo VM. It seems to mostly alternate between timing out on baud selection or fetching device info. Or pinging...

How is your 3DM-GX4 configured? Or should it not matter since this node is doing configuration as well?

**Comment by gareth-cross** [comment]
How frustrating. I did not configure my GX4 with any other software - I have only ever used it with this driver. I was about to suggest trying to change the timeout value but I guess that's no good.

In the cases where the driver made it past the baud-rate selection, what firmware version did it output? I have two 3DM-GX4s here, both firmware version 1104.

**Comment by ryfallon** [comment]
Mine is also FW 1104. I'm going to call it a day for the moment but I think it'll be worth checking if receiveResponse and std::chrono are working correctly tomorrow. Thanks for your responses and if you think of anything else let me know :)

**Comment by ryfallon** [comment]
I've managed to further narrow it down to handleRead. Apparently, every so often, the 'u' and 'e' (kSyncMSB and kSyncLSB) get split up into consecutive calls, and so handleRead doesn't know to continue processing the packet (because the 'u' gets popped), hence the timeout. I still don't know why it does this, but this seems to be the root of the matter. I've tried to circumvent this by not popping the 'u' if it sees it, but that introduces other issues. What would be the best way to ensure that the 'u' stays in the front of queue_ across two calls of handleRead?

**Comment by gareth-cross** [comment]
Ah, I see what you mean. This code seems innocuous at first but in the case where the header is broken up it may cause issues. I think one solution is simply not to process the queue (though _only_ in the idle state) until there are >= 2 bytes available. I will attempt this and see if it breaks anything. You may wish to see if this check solves your problem.

**Comment by gareth-cross** [comment]
Ok I have refactored this piece of the code and believe the issue to be solved. I do not have the IMU with me at the moment. I will test the solution and push the corrected code tomorrow morning.

**Comment by gareth-cross** [comment]
Hi @ryfallon, can you pull the branch `fix/read-errors` from [here](https://github.com/gareth-cross/imu_3dm_gx4/tree/fix/read-errors). I cleaned up the code so the queue is only popped in one place. I realize now the old design was error prone. Can you test this and let me know if it helps?

**Comment by ryfallon** [comment]
Sorry for the delay but I won't be able to test it until Monday. I'll let you know how it goes then.

**Comment by ryfallon** [comment]
I just tested it and it's very close. It now gets through most of the initial configuration just fine, but it's now hanging up on "Enabling filter measurements", after which it shows a lot of "Dropped packet with mismatched checksum". This goes away if I change the .launch to disable filter measurements so maybe it's just bad constants. Once I tried it without the filter, though, the ros node quickly threw a "Time is out of dual 32-bit range" exception. I'm using a 32-bit VM and this will eventually be running on ARM, could that be an issue?

**Comment by gareth-cross** [comment]
I'll take a look again and see if I can replicate the checksum issue. What is responsible for the 'time' exception - is ROS throwing it or something else?

**Comment by ryfallon** [comment]
I think ROS is throwing it. I looked up the error and there was a similar problem in the other microstrain driver (https://code.ros.org/trac/ros-pkg/ticket/5601) that suggested a bad conversion of time datatypes to the ROS datatype when calculating/referencing header stamps, usually involving ros::time::now(), but your code doesn't outwardly seem to call time in the same way that caused the problem so I'm not sure.

Another user seemed to think it could be just a VM problem since in their case it was solved when they ran it on the actual hardware. I'll try to run it native to see if that's the case.

**Comment by gareth-cross** [comment]
I have observed the checksum issue before on certain hardware. I was able to replicate the problem again on my machine (though not very often) by turning on a high data rate (1000Hz) and high baudrate (> 900000). Here is an example of what happens:

![issue](https://cloud.githubusercontent.com/assets/5404001/6114199/7fd07e62-b06a-11e4-809c-ceeb5656dce0.png)

The entire payload is received, but the last byte of the checksum (which should be `0x7c` in this case) is not received. The `Handling Read` message is printed in handleRead, called from pollInput. It reads a full 10 bytes (the size of the buffer), but the  `3a` is followed by a new packet `75 65` instead of the correct checksum byte.

I do not know what causes this issue, although it happens frequently on another machine we have when some unrelated settings in `/etc/network/interfaces` are configured in a certain manner. Very strange.

Let me know if running on hardware instead of a VM helps at all.

**Comment by ryfallon** [comment]
I was finally able to run it on my hardware and it seems to run stably, which is great. However, I'm still getting all of those mismatched checksums once it gets past configuration and into the main data-reading loop.

Since you were able to force the checksum problem to happen by cranking up the data/baud rate, I tried decreasing that when running but the issue persisted.

I'm not terribly concerned with the checksums themselves. How detrimental would it be to only check for the MSB? Also, what configuration difference is there with the machine you mentioned?

**Comment by gareth-cross** [comment]
On my laptop VM (Ubuntu 14.04, gcc 4.8.2) I get the problem maybe once every couple of seconds when running the IMU at 1000Hz.

On our other machine (Intel NUC, Ubuntu 14.04, gcc 4.9, not a VM) the problem occurs to about 10% of packets if there is a USB-Ethernet networking device configured in /etc/network/interfaces which is not present (not plugged in).

How bad is the packet loss? If you request 250Hz, what does `rostopic hz` report as the real rate?

**Comment by ryfallon** [comment]
Hmm, well at the moment it's 100% loss due to mismatched checksum, again only for data (or non-config) packets. I'm running at the default 100Hz and 115200 baud still.

**Comment by gareth-cross** [comment]
Can you pull the latest from `fix/read-errors` and copy some example output (line the screenshot I posted). I just want to see if it is an identical issue.

**Comment by ryfallon** [comment]
Handling read : 7e b 11 5a 2 75 65 80 30 e 
Not interested in this [N]ACK!
SyncMSB: 75
SyncLSB: 65
Descriptor: 80
Length: 30
Payload: e 4 ba 88 81 2c 3c 1b 32 e bf 7f d1 af e 5 b9 c5 49 7c 3a 58 f7 c3 3a 73 6e 88 e 6 be 56 e7 51 be 1 15 1b 3e eb ae 14 6 17 44 7e b 11 
Check MSB: 5a
Check LSB: 2
Handling read : 4 ba ba c6 b0 3c 9 40 ed bf 
Handling read : 80 32 3d e 5 ba 9b 7d aa 38 
Handling read : f1 c2 94 3a f7 c7 46 e 6 be 
Handling read : 56 a5 45 be 0 94 dd 3e ea dc 
Handling read : 1c 6 17 44 7e a f8 34 9d 75 
Not interested in this [N]ACK!
SyncMSB: 75
SyncLSB: 65
Descriptor: 80
Length: 30
Payload: e 4 ba ba c6 b0 3c 9 40 ed bf 80 32 3d e 5 ba 9b 7d aa 38 f1 c2 94 3a f7 c7 46 e 6 be 56 a5 45 be 0 94 dd 3e ea dc 1c 6 17 44 7e a f8 
Check MSB: 34
Check LSB: 9d
Handling read : 65 80 30 e 4 ba e8 61 22 3c 
Handling read : a 8c da bf 7f 96 a5 e 5 38 
Handling read : 1 8b 60 ba b8 fb 28 3a b7 67 
Handling read : f8 e 6 be 55 dd 8a be 1 38 
Handling read : 82 3e e9 64 4 6 17 44 7e b 
Handling read : e0 62 f4 75 65 80 30 e 4 bb 
Not interested in this [N]ACK!
SyncMSB: 75
SyncLSB: 65
Descriptor: 80
Length: 30
Payload: e 4 ba e8 61 22 3c a 8c da bf 7f 96 a5 e 5 38 1 8b 60 ba b8 fb 28 3a b7 67 f8 e 6 be 55 dd 8a be 1 38 82 3e e9 64 4 6 17 44 7e b e0 
Check MSB: 62
Check LSB: f4
Handling read : 1 de a 3c 1d 5b cd bf 7f b0 
Handling read : 7c e 5 ba 84 a 5b ba 13 34 
Handling read : 6d 39 5f c3 68 e 6 be 55 af 
Handling read : 86 be 2 55 86 3e ea af 98 6 
Handling read : 17 44 7e e 13 7b b6 75 65 80 
Warning: Dropped packet with mismatched checksum
Expected 3578 but received b67b

I should mention most of the output showed "Not interested in [N]ACK" with periodic dropped packet from checksum. From looking at the ones with mismatched checksum the received wasn't even close to the expected, like above, so perhaps it isn't a simple off-by-one.

**Comment by ryfallon** [comment]
I discovered I was getting satisfactory output on the ros topics while it runs, despite a few packet drops. What I really need for my application is the orientation so I did need to enable the filter stream, which still caused a timeout when it got to the commands to enable accel and mag filter updates. If I comment out that command right after enabling the filter stream I get the filter output just fine. Using your debug output I found out that the IMU was returning a malformed ACK for that command (a 0x04 in place of the expected 0x0D for command set), so for whatever reason, the fault is in the hardware. Just to make sure, are you able to issue those commands (imu.enableMeasurements, imu.enableBiasEstimation) without any problems?

If so I'd say this issue can be closed as I don't see any remaining problems with your code.

**Comment by gareth-cross** [comment]
Apologies for not responding to your previous message - was away on a field expedition. I do not have an issue with `enableMeasurements` or `enableBiasEstimation` on my IMU. Admittedly, I usually do not run the IMU with the filter enabled, so this code is not as frequently tested. The malformed ACK is similar to the issue I described earlier where the second byte of the checksum is simply missing from the input stream.

Unfortunately I'm not sure how to continue debugging this, as the issue _seems_ to take place between packet formation (on the IMU) and the call to the low-level `read` command.

I have sent an email to Microstrain to see if similar issues have been reported before.

**Comment by gareth-cross** [comment]
New development: 

I recently acquired a brand new 3DM-GX4-25, also firmware 1104. With this one I can replicate the timeout-during-baud-rate issue (still not 100% clear on why).

I have added a `verbose` flag to enable logging to stdout (still in my personal fork). When `verbose` is true, the timeout does not happen. When `verbose` is false, it happens repeatedly. This suggests either a timing issue or something to do with the combination of console and serial I/O happening simultaneously.

@ryfallon, if you have a moment, could you pull from `fix/read-errrors` and try running with `verbose` on and off? Let me know if it fails repeatably when verbose is off but works if verbose is on.
